import { Injectable } from '@angular/core';
import { Cocina } from '../models/cocina.model';

@Injectable({
  providedIn: 'root'
})
export class CocinaService {

  cocina1  = new Cocina("C001", "../../assets/cocina1.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!", 100.99, "Blanco");
  cocina2  = new Cocina("C002", "../../assets/cocina2.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!", 121.99, "Blanco");
  cocina3  = new Cocina("C003", "../../assets/cocina3.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!", 151.99, "Blanco");
  cocina4  = new Cocina("C004", "../../assets/cocina4.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dictacommodi impedit a exercitationem voluptates non reprehenderit earum voluptatum ab suscipit unde doloremque error deleniti autem reiciendis,accusantium, nam dolores!", 175.99, "Blanco");

  cocina : Array<Cocina> = new Array<Cocina>(this.cocina1, this.cocina2, this.cocina3, this.cocina4);
  
  getCocinas(){
    return this.cocina;
  }

  constructor() { }
}
